### ISSUE TITLE
Is this module deprecated/unmaintained?

### ISSUE THREAD

**Issue by luiseduardobrito** [nathanpeck/clui#18]
No response for over a year in the opened issues, documentation errors and other commits in a while. Is this module being maintained? 

If not, you should notify users about it in readme and in the NPM, I see a lot of active downloads for this module in its profile and a lot of developers may might experience troubles in future updates in NodeJS itself.

<img width="361" alt="screen shot 2017-06-12 at 16 40 24" src="https://user-images.githubusercontent.com/1218520/27051825-e7cdb934-4f8d-11e7-8cb1-8d105527cb49.png">

**Comment by nathanpeck** [comment]
I am currently unable to maintain this project due to a contractual intellectual property clause that would run the risk of me automatically transferring ownership to Amazon if I modified the code. (I think I can get an exemption but its a process, one of the downsides of big software companies is it makes it hard to do open source sometimes). But I welcome collaborators who can help out. I just added one new collaborator who reached out, and if you are interested in becoming a collaborator as well let me know!

**Comment by artokun** [comment]
I'm taking a look right now and testing PRs. I will be working on fixes this week and start pushing out updates asap.

**Comment by luiseduardobrito** [comment]
Great, I'll try to contribute and send PRs if we actually use this module in production.

Thanks for the responses!

**Comment by artokun** [comment]
Closing this since we are actively maintaining this package

**Comment by DanielRuf** [comment]
It seems it is not actively maintained anymore.
